server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: trajet-service
          uri: http://localhost:8088
          predicates:
            - Path=/trajet/**

